### ISSUE TITLE
Board squeeze on mobile

### ISSUE THREAD

**Issue by tannerkrewson** [kevin-shannon/sudoku#4]
It looks normal whenever I open it on my phone, but when I tap on a box to enter a number, the keyboard opens, and the width of the grid gets a bit smaller. Lmao might be hard to diagnose this one

**Comment by kevin-shannon** [comment]
I noticed this too lol, tried to fix it in the last commit but failed.... i'll look more into it.

**Comment by tannerkrewson** [comment]
i think the issue is that the inputs have some kind of minimum height, and if you try and make their container smaller, they just won't let it. so, the `height` applied to the table is not being used

**Comment by kevin-shannon** [comment]
yeah, i think it's the font size that;s minimizing the height  of the input which is fixed off starting tr height, if we could somehow update font size on event or not resize grid when the keyboard pops up this should be fixed.

**Comment by kevin-shannon** [comment]
054aae11245f8717cabd477c86848d769f1c8549
